import test from 'node:test';
import assert from 'node:assert/strict';
import {createAppsScriptHarness} from './helpers/apps-script-harness.js';
import {validateMemberMealEdit,editMemberMeals} from './member-meals-edit.js';
const headers=['key','householdId','schemaVersion','updatedAt','updatedBy','status','json','notes'];
const groceries=[{item:'Milk',qty:'1',done:true}];
const days=[{date:'2026-10-05',meal:'Soup',prep:'Heat'}];
function harness(){const h=createAppsScriptHarness();h.properties.set('MEMBER_MEALS_EDIT','enabled');h.properties.set('MEMBER_DASHBOARD','enabled');h.sheet('Users',[['userId','status','displayName','identityProvider','providerSubject','email','createdAt','updatedAt','notes'],['u1','active','','offline','fixture','','','','']]);h.sheet('Households',[['householdId','status','name','createdAt','updatedAt','notes'],['home','active','','','','']]);h.sheet('Household Memberships',[['membershipId','householdId','userId','role','status','createdAt','updatedAt','notes'],['m1','home','u1','secondary','active','','','']]);const raw={householdId:'home',version:7,approved:{days:[{date:'2026-10-05',meal:'Old meal',prep:'',recipe:{instructions:'Old recipe'}}],groceryList:[],weekStart:'2026-10-05'},draft:{private:'preserved'},mealHistory:['preserved'],rules:{keep:true}};h.sheet('Meals',[headers,['neighbor','other',1,'','','approved',JSON.stringify({householdId:'other',version:9}),'neighbor notes'],[],['home','home',1,'','','approved',JSON.stringify(raw),'preserve notes']]);return h;}
const body=(extra={})=>({token:'offline-service-token',resource:'member_meals_edit',operation:'edit_groceries',householdId:'home',actor:'u1',expectedVersion:7,rows:groceries,...extra});
test('grocery changes update exact physical row, preserve other fields, and flush under lock',()=>{const h=harness(),before=h.rows('Meals');assert.equal(h.post(body()).newVersion,8);const after=h.rows('Meals');assert.deepEqual(after[1],before[1]);assert.deepEqual(after[2],before[2]);assert.equal(after[3][7],'preserve notes');const raw=JSON.parse(after[3][6]);assert.deepEqual(raw.approved.groceryList,groceries);assert.deepEqual(raw.draft,{private:'preserved'});assert.deepEqual(raw.mealHistory,['preserved']);assert.deepEqual(raw.rules,{keep:true});assert.equal(h.events.find(e=>e.type==='written').row,4);assert.ok(h.events.filter(e=>['written','flush'].includes(e.type)).every(e=>e.held));assert.equal(h.held,false);});
test('approved meal edit preserves dates and clears an old recipe when meal changes',()=>{const h=harness();assert.equal(h.post(body({operation:'edit_meals',rows:days})).ok,true);const raw=JSON.parse(h.rows('Meals')[3][6]);assert.equal(raw.approved.days[0].meal,'Soup');assert.equal(raw.approved.days[0].recipe,undefined);assert.equal(raw.approved.weekStart,'2026-10-05');});
test('same version contention produces one commit and one conflict; no blind overwrite',()=>{const h=harness();assert.equal(h.post(body()).ok,true);assert.equal(h.post(body({operation:'edit_meals',rows:days})).error,'MEMBER_MEALS_CONFLICT');assert.equal(JSON.parse(h.rows('Meals')[3][6]).version,8);});
test('gate, foreign target, revoked member, duplicate target and invalid patches fail without writes',()=>{
 for(const mutate of [h=>h.properties.delete('MEMBER_MEALS_EDIT'),h=>h.properties.delete('MEMBER_DASHBOARD'),h=>{const rows=h.rows('Household Memberships');rows[1][4]='revoked';h.sheet('Household Memberships',rows);},h=>{const rows=h.rows('Meals');const raw=JSON.parse(rows[3][6]);raw.householdId='other';rows[3][6]=JSON.stringify(raw);h.sheet('Meals',rows);},h=>{const rows=h.rows('Meals');rows.push([...rows[3]]);h.sheet('Meals',rows);}]){const h=harness();mutate(h);assert.equal(h.post(body()).ok,false);assert.equal(h.events.filter(e=>e.type==='write').length,0);}
 const h=harness();for(const extra of [{actor:'someone'},{householdId:'other'},{rows:[{...groceries[0],role:'principal'}]},{operation:'edit_meals',rows:[{...days[0],date:'2026-10-06'}]}])assert.equal(h.post(body(extra)).ok,false);assert.equal(h.events.filter(e=>e.type==='write').length,0);
});
test('validation agrees in both layers for typed fields, blank rules and impossible dates',()=>{const h=harness();for(const [operation,rows]of [['edit_groceries',[]],['edit_groceries',groceries],['edit_meals',days]])assert.equal(validateMemberMealEdit(operation,rows),h.call('validMemberMealEdit_',operation,rows));for(const rows of [[{item:'',qty:'1',done:false}],[{item:'Food',qty:1,done:false}],[{item:'Food',qty:'',done:'true'}]]){assert.equal(validateMemberMealEdit('edit_groceries',rows),false);assert.equal(h.post(body({rows})).error,'MEMBER_MEALS_INVALID');}assert.equal(validateMemberMealEdit('edit_meals',[{...days[0],date:'2026-02-30'}]),false);});
test('postwrite failure preserves UNKNOWN semantics and releases lock; readback reconciles',()=>{for(const type of ['written','flush']){const h=harness();h.setFault(event=>{if(event.type===type)throw Error('private fault');});assert.equal(h.post(body()).error,'MEMBER_MEALS_OUTCOME_UNKNOWN');assert.equal(h.held,false);assert.equal(JSON.parse(h.rows('Meals')[3][6]).version,8);}});
test('adapter does not expose backend errors and treats lost responses as unknown',async t=>{const oldFetch=globalThis.fetch,oldUrl=process.env.MC_SYNC_URL,oldToken=process.env.MC_SYNC_TOKEN;process.env.MC_SYNC_URL='https://offline.invalid';process.env.MC_SYNC_TOKEN='offline';t.after(()=>{globalThis.fetch=oldFetch;for(const[key,value]of [['MC_SYNC_URL',oldUrl],['MC_SYNC_TOKEN',oldToken]]){if(value===undefined)delete process.env[key];else process.env[key]=value;}});const payload={actor:'u1',householdId:'home',operation:'edit_groceries',expectedVersion:7,rows:groceries};for(const response of [()=>{throw Error('SECRET');},()=>new Response('invalid'),()=>new Response(JSON.stringify({ok:false,error:'SECRET'})),()=>new Response(JSON.stringify({ok:true,previousVersion:7,newVersion:99}))]){globalThis.fetch=response;await assert.rejects(editMemberMeals(payload),error=>error.code==='MEMBER_MEALS_OUTCOME_UNKNOWN'&&!error.message.includes('SECRET'));}globalThis.fetch=()=>new Response(JSON.stringify({ok:true,previousVersion:7,newVersion:8}));assert.equal((await editMemberMeals(payload)).newVersion,8);});
test('member and existing human Meals writers share lock/version contention in both orders',()=>{
 for(const memberFirst of [true,false]){const h=harness();h.sheet('Meals',[headers,h.rows('Meals')[3]]);if(memberFirst){assert.equal(h.post(body()).ok,true);assert.throws(()=>h.call('writeMealsWithLock_',{draft:{days:[]}},'save_draft','offline-principal',7),/CONFLICT/);}else{assert.equal(h.call('writeMealsWithLock_',{draft:{days:[]}},'save_draft','offline-principal',7).version,8);assert.equal(h.post(body()).error,'MEMBER_MEALS_CONFLICT');}assert.equal(h.events.filter(e=>e.type==='acquire').length,2);assert.equal(h.events.filter(e=>e.type==='release').length,2);assert.equal(JSON.parse(h.rows('Meals')[1][6]).version,8);}
});
