import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {createAppsScriptHarness,projectHeaders,projectRow} from './helpers/apps-script-harness.js';
import {projectMemberDashboard,readMemberDashboard} from './member-dashboard.js';
import {validateSetupPreferences,callMemberSetup} from './member-setup.js';
import {authorize} from './authorization.js';
import {requireMissionControlOrigin} from './origin.js';
const legacyHeaders=['id','name','area','status','priority','attention','owner','description','outcome','doneDefinition','currentState','nextAction','waitingOn','waitingSince','followupDate','deadline','milestone','milestoneDate','progress','tags','notes','dependencyId','lastUpdate','lastUpdatedAt','lastUpdatedBy','financeData','agendaData'];
const mealHeaders=['key','householdId','schemaVersion','updatedAt','updatedBy','status','json','notes'];
function harness(withData=true){
 const h=createAppsScriptHarness();h.properties.set('MEMBER_DASHBOARD','enabled');
 h.sheet('Users',[['userId','status','displayName','identityProvider','providerSubject','email','createdAt','updatedAt','notes'],['u1','active','Offline user','offline','SECRET','SECRET','','','']]);
 h.sheet('Households',[['householdId','status','name','createdAt','updatedAt','notes'],['butler-household','active','Offline household','','',''],['other','active','Other','','','']]);
 h.sheet('Household Memberships',[['membershipId','householdId','userId','role','status','createdAt','updatedAt','notes'],['m1','butler-household','u1','secondary','active','','','']]);
 if(!withData)return h;
 const row=Array(legacyHeaders.length).fill('');row[0]='finance';row[25]=JSON.stringify({asOf:'2026-10-05',budget:{categories:[{name:'Food',planned:500}],income:'SECRET'},budgetReconciliation:{categories:[{name:'Food',spent:200,notes:'SECRET'}]},accounts:[{balance:12345}],debt:'SECRET',currentMonthTransactions:[{description:'SECRET'}]});row[26]='SECRET';h.sheet('Projects',[legacyHeaders,row]);
 h.sheet('Meals',[mealHeaders,['meal','butler-household',1,'','','approved',JSON.stringify({householdId:'butler-household',approved:{weekStart:'2026-10-05',days:[{date:'2026-10-05',meal:'Soup',prep:'Heat',calendarConstraint:'SECRET'}],groceryList:[{item:'Bread',qty:'1',done:false,sourceMeal:'SECRET'}]},draft:'SECRET',mealHistory:'SECRET'}),'SECRET']]);
 const shared=projectRow({id:'family'});shared[8]='household:shared';shared[6]='Family dinner';h.sheet('Project Resources',[projectHeaders,projectRow({id:'private'}),shared,projectRow({id:'foreign',householdId:'other'})]);return h;
}
const payload=extra=>({token:'offline-service-token',resource:'member_dashboard',operation:'read',actor:'u1',householdId:'butler-household',...extra});
const writes=h=>h.events.filter(e=>['write','append','insert','flush'].includes(e.type));
test('backend minimizes raw snapshots before transport and never mutates a sheet',()=>{
 const h=harness(),before=['Projects','Meals','Project Resources','Users'].map(name=>h.rows(name));const body=h.post(payload());assert.equal(body.ok,true);assert.ok(!JSON.stringify(body).includes('SECRET'));assert.ok(!JSON.stringify(body).includes('balance'));assert.ok(!JSON.stringify(body).includes('12345'));const result=projectMemberDashboard(body,'butler-household');assert.equal(result.dashboard.budget.remaining,300);assert.equal(result.dashboard.meals.days[0].meal,'Soup');assert.deepEqual(result.dashboard.family,[{id:'family',name:'Family dinner',lifecycle:'active'}]);assert.deepEqual(before,['Projects','Meals','Project Resources','Users'].map(name=>h.rows(name)));assert.equal(writes(h).length,0);assert.equal(h.held,false);
});
test('missing data stays missing without creating sheets or returning samples',()=>{const h=harness();for(const name of ['Projects','Meals','Project Resources'])h.sheet(name,[]);const body=h.post(payload());assert.deepEqual(body.sections,{budget:'unavailable',meals:'unavailable',family:'unavailable'});assert.equal(writes(h).length,0);const empty=createAppsScriptHarness();empty.properties.set('MEMBER_DASHBOARD','enabled');assert.equal(empty.post(payload()).ok,false);assert.equal(writes(empty).length,0);});
test('budget supports separate reconciliation column without leaking its extra metadata',()=>{const h=harness(),rows=h.rows('Projects');rows[0].push('budgetData');rows[1].push(JSON.stringify({reconciliation:{categories:[{name:'Food',spent:250,note:'SECRET'}]},accounts:'SECRET'}));h.sheet('Projects',rows);const body=h.post(payload());assert.equal(projectMemberDashboard(body,'butler-household').dashboard.budget.spent,250);assert.ok(!JSON.stringify(body).includes('SECRET'));});
test('ambiguous budgets, duplicate meals and global resource collisions fail closed per section',()=>{
 const h=harness(),projects=h.rows('Projects'),meals=h.rows('Meals'),resources=h.rows('Project Resources');projects.push([...projects[1]]);meals.push([...meals[1]]);resources.push(projectRow({id:'family',householdId:'other'}));h.sheet('Projects',projects);h.sheet('Meals',meals);h.sheet('Project Resources',resources);const body=h.post(payload());assert.deepEqual(body.sections,{budget:'unavailable',meals:'unavailable',family:'unavailable'});assert.deepEqual(body.familyResources,[]);assert.equal(writes(h).length,0);
});
test('wrong household, actor, extended role and revoked membership cannot read data',()=>{
 const h=harness();for(const extra of [{householdId:'other'},{actor:'someone-else'},{actor:'u1',role:'principal'}])assert.equal(h.post(payload(extra)).ok,false);
 for(const role of ['extended','secondary']){const member=h.rows('Household Memberships');member[1][3]=role;member[1][4]=role==='secondary'?'revoked':'active';h.sheet('Household Memberships',member);assert.equal(h.post(payload()).error,'MEMBER_SETUP_FORBIDDEN');}assert.equal(writes(h).length,0);
});
test('another active household never receives Butler legacy finance',()=>{const h=harness(),member=h.rows('Household Memberships');member[1][1]='other';h.sheet('Household Memberships',member);const body=h.post(payload({householdId:'other'}));assert.equal(body.ok,true);assert.equal(body.sections.budget,'missing');assert.equal(body.budgetSnapshot,null);assert.equal(body.sections.meals,'missing');assert.equal(writes(h).length,0);});
test('nested foreign Meals household and private/draft/archive family resources stay excluded',()=>{const h=harness(),meals=h.rows('Meals');meals[1][6]=JSON.stringify({householdId:'other',approved:{days:[]}});h.sheet('Meals',meals);const resources=h.rows('Project Resources');resources[2][4]='archived';h.sheet('Project Resources',resources);const body=h.post(payload());assert.equal(body.sections.meals,'unavailable');assert.deepEqual(body.familyResources,[]);});
test('read gate independently rejects even valid private service token',()=>{const h=harness();h.properties.delete('MEMBER_DASHBOARD');assert.equal(h.post(payload()).error,'MEMBER_DASHBOARD_DISABLED');assert.equal(writes(h).length,0);assert.equal(h.events.length,0);});
test('adapter rejects malformed household/section contracts and strips unknown fields',()=>{const h=harness(),body=h.post(payload());body.secret='SECRET';const result=projectMemberDashboard(body,'butler-household');assert.ok(!JSON.stringify(result).includes('SECRET'));assert.throws(()=>projectMemberDashboard(body,'other'));assert.throws(()=>projectMemberDashboard({...body,sections:{...body.sections,budget:'made-up'}},'butler-household'));assert.throws(()=>projectMemberDashboard({...body,budgetSnapshot:null},'butler-household'));});
function route(t,{gate=true,role='secondary',signedIn=true,transport}={}){
 const h=harness(),calls=[],previous={};for(const [name,value] of Object.entries({MC_AUTHORIZED_PARTIES:'https://offline.invalid',MC_SYNC_URL:'https://offline.invalid/exec',MC_SYNC_TOKEN:'offline-service-token'})){previous[name]=process.env[name];process.env[name]=value;}
 const oldFetch=globalThis.fetch;globalThis.fetch=async(_url,options)=>{const body=JSON.parse(options.body);calls.push(body);return transport?transport(h,body):new Response(JSON.stringify(h.post(body)));};t.after(()=>{globalThis.fetch=oldFetch;for(const[name,value]of Object.entries(previous)){if(value===undefined)delete process.env[name];else process.env[name]=value;}});
 const ctx=vm.createContext({process:{env:{MC_DEFAULT_HOUSEHOLD_ID:'butler-household',MC_MEMBER_DASHBOARD:gate?'enabled':''}},Number,Set,requireMissionControlOrigin,authorize,validateSetupPreferences,callMemberSetup,readMemberDashboard,installClerkIdentityAdapter(){},installUpstreamDirectoryAdapter(){},requireVerifiedIdentity:async()=>{if(!signedIn)throw Object.assign(new Error('private'),{code:'UNAUTHENTICATED',statusCode:401});return{provider:'offline',subject:'SECRET'};},resolveAccessContext:async(_identity,householdId)=>({user:{userId:'u1',status:'active'},household:{householdId,status:householdId==='butler-household'?'active':'inactive'},membership:{userId:'u1',householdId,role,status:'active'}})});
 const source=fs.readFileSync(new URL('../api/v1/member.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export default async function handler','globalThis.handler=async function handler');vm.runInContext(source,ctx);
 return{h,calls,async request(body={operation:'dashboard'},origin='https://offline.invalid'){let status=200,result;const headers={};await ctx.handler({method:'POST',body,headers:{origin,'sec-fetch-site':'same-origin'}},{setHeader(k,v){headers[k]=v;return this},status(v){status=v;return this},json(v){result=v;return this}});return{status,result,headers};}};
}
test('member API runs real backend projection using server authority',async t=>{const f=route(t),r=await f.request();assert.equal(r.status,200);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(f.calls[0].actor,'u1');assert.equal(f.calls[0].resource,'member_dashboard');assert.equal(r.result.dashboard.budget.spent,200);assert.ok(!JSON.stringify(r.result).includes('SECRET'));assert.equal(writes(f.h).length,0);});
test('anonymous, extended, gate-off and authority extras never reach dashboard upstream',async t=>{for(const options of [{signedIn:false},{role:'extended'},{gate:false}]){const f=route(t,options);assert.ok((await f.request()).status>=400);assert.equal(f.calls.length,0);}const f=route(t);for(const body of [{operation:'dashboard',actor:'other'},{operation:'dashboard',householdId:'other'},{operation:'dashboard',preferences:{}}])assert.ok((await f.request(body)).status>=400);assert.equal((await f.request({operation:'dashboard'},'https://evil.invalid')).status,403);assert.equal(f.calls.length,0);});
test('backend denial, body loss and malformed response never become visible shared data',async t=>{const f=route(t);f.h.properties.delete('MEMBER_DASHBOARD');assert.equal((await f.request()).result.code,'MEMBER_DASHBOARD_DISABLED');for(const transport of [()=>new Response('not JSON'),()=>{throw Error('SECRET');},()=>new Response(JSON.stringify({ok:true,householdId:'other'}))]){const f=route(t,{transport});const r=await f.request();assert.equal(r.status,503);assert.ok(!JSON.stringify(r.result).includes('SECRET'));}});

test('genuinely absent data tabs stay missing and are never initialized',()=>{const h=harness(false);const body=h.post(payload());assert.deepEqual(body.sections,{budget:'missing',meals:'missing',family:'missing'});assert.equal(body.profile,null);assert.equal(writes(h).length,0);});
