import fs from "node:fs";
const s=fs.readFileSync(new URL("../google_apps_script_Code.gs",import.meta.url),"utf8");
function must(re,msg){if(!re.test(s))throw new Error(msg)}
must(/function readProjectResourceRecords_\(\).*sheetRow:i\+2/s,"physical Project Resource row identity missing");
must(/if\(rec\)sh\.getRange\(rec\.sheetRow,1,1,16\)/,"Project Resource writer is not using physical sheet row");
must(/current&&requiredHouseholdId&&current\.householdId!==requiredHouseholdId/,"target Project household check missing");
must(/resource==="project_trusted_operation"[\s\S]*?LockService\.getScriptLock\(\)/,"trusted Project operation lacks ScriptLock");
must(/function processAgentOperations\(\)\{const lock=LockService\.getScriptLock\(\)/,"Dot Project operations lack common ScriptLock");
must(/function bootstrapProjectResources\(\)\{const lock=LockService\.getScriptLock\(\)/,"Project Resource refresh lacks common ScriptLock");
must(/targetLifecycle==="active"\)[\s\S]*?raw\.completed=false;raw\.archived=false;raw\.deleted=false/,"active lifecycle metadata incoherent");
must(/targetLifecycle==="archived"\)[\s\S]*?raw\.completed=false;raw\.archived=true;raw\.deleted=false/,"archived lifecycle metadata incoherent");
must(/targetLifecycle==="deleted"\)[\s\S]*?raw\.completed=false;raw\.deleted=true;raw\.archived=false/,"deleted lifecycle metadata incoherent");
must(/targetLifecycle==="completed"\)[\s\S]*?raw\.completed=true;raw\.archived=false;raw\.deleted=false/,"completed lifecycle metadata incoherent");
must(/projectOperationFingerprintMatches_\(prior,body\)/,"operationId fingerprint dedupe missing");
must(/status==="SUCCESS"\)return json_\(Object\.assign\(\{\},saved,\{replayed:true\}\)\)/,"successful operation replay behavior missing");
must(/SpreadsheetApp\.flush\(\)[\s\S]*?finally\{lock\.releaseLock\(\)\}/,"shared Project lock does not flush before independent release");
if(/finally\{SpreadsheetApp\.flush\(\);lock\.releaseLock\(\)\}/.test(s))throw new Error("flush can still prevent explicit lock release");
must(/Project mutation committed but success audit persistence failed/,"post-commit audit failure is not represented as unknown outcome");
must(/definitive=\/\^\(INVALID\|CONFLICT\|FORBIDDEN\):\//,"definitive pre-commit failure classification missing");
must(/function isProjectCalendarDate_\(v\)/,"Apps Script real calendar date validator missing");
must(/Date\.UTC\(y,m-1,d\)/,"Apps Script calendar date validator does not round-trip the date");
must(/patch date .*real YYYY-MM-DD calendar date or blank/,"Apps Script date validation missing");
if(/\^\\\\d\{4\}-\\\\d\{2\}-\\\\d\{2\}\$/.test(s))throw new Error("Apps Script Project date regex is double escaped");
console.log(JSON.stringify({ok:true,projectAppsScriptContracts:true}));
